export const matchTable = ['Shipper -- Consignee',
  'Jacksonville Terminal -- Greenland RMC',
  'Melbourne Terminal -- South Orange RMC',
  'Melbourne Terminal -- Orlando Block',
  'Melbourne Terminal -- Greenbay RMC',
  'Jahna Greenbay -- South Orange RMC',
  'Jahna Greenbay -- Daytona RMC',
  'JAHNA GREENBAY -- Melbourne RMC',
  'CORKSCREW MINE -- VENICE RMC',
  'JAHNA GREENBAY -- ST CLOUD RMC']
